
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Sep 15 20:48:04 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 50;
  public static final int CONST = 3;
  public static final int CHAR = 20;
  public static final int REMOVE = 59;
  public static final int HASHHASH = 53;
  public static final int NAMESPACE = 13;
  public static final int LPAREN = 44;
  public static final int SEMI = 39;
  public static final int HASH = 38;
  public static final int CONTINUE = 10;
  public static final int INT = 19;
  public static final int MINOP = 57;
  public static final int FOR = 11;
  public static final int MINUS = 23;
  public static final int RPAREN = 45;
  public static final int STATIC = 12;
  public static final int AND = 33;
  public static final int LT = 31;
  public static final int IN = 60;
  public static final int OR = 34;
  public static final int COMMA = 42;
  public static final int BOOL = 21;
  public static final int CLASS = 14;
  public static final int INC = 36;
  public static final int DIV = 25;
  public static final int GEQ = 30;
  public static final int PLUS = 22;
  public static final int IF = 17;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 51;
  public static final int EQUAL = 35;
  public static final int LAMBDA = 52;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int MOD = 26;
  public static final int NEQ = 28;
  public static final int BREAK = 9;
  public static final int IDENT = 18;
  public static final int VOID = 8;
  public static final int EQ = 27;
  public static final int COLON = 41;
  public static final int UNION = 54;
  public static final int LBRACE = 48;
  public static final int LANGLE = 46;
  public static final int ELSE = 16;
  public static final int READ = 6;
  public static final int DIFFERENCE = 56;
  public static final int DCOLON = 40;
  public static final int MAXOP = 58;
  public static final int RBRACE = 49;
  public static final int RANGLE = 47;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int DEC = 37;
  public static final int INTERSECT = 55;
  public static final int GT = 29;
  public static final int PRINT = 5;
}

